swagger: '2.0'
info:
  contact:
    name: OneLogin
    url: 'https://support.onelogin.com'
  description: OpenAPI Specification for OneLogin
  title: OneLogin API
  version: 1.0.0
host: api.us.onelogin.com
basePath: /
schemes:
  - https
paths:
  /api/1/events:
    get:
      security:
        - OAuth2:
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - Events
      description: Get Events
      operationId: getEvents
      summary: Get Events
  /api/1/events/types:
    get:
      tags:
        - Events
      description: Get Event types
      operationId: getEventTypes
      summary: Get Event Types
  '/api/1/events/{event_id}':
    get:
      security:
        - OAuth2:
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - Events
      description: Get Event By ID
      operationId: getEventById
      summary: Get Event by ID
  /api/1/groups:
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Groups
      description: Get Groups
      operationId: getGroups
      summary: Get Groups
  '/api/1/groups/{group_id}':
    get:
      security:
        - OAuth2:
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - Groups
      description: Get Group By ID
      operationId: getGroupById
      summary: Get Group by ID
  /api/1/invites/get_invite_link:
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Invite Links
      description: Generate Invite Link
      operationId: getInviteLink
      summary: Generate Invite Link
  /api/1/invites/send_invite_link:
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Invite Links
      description: Send Invite Link
      operationId: sendInviteLink
      summary: Send  Invite Link
  /api/1/privileges:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: List Privileges
      operationId: listPriveleges
      summary: List Privileges
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Create privilege
      operationId: createPrivilege
      summary: Create a Privilege
  '/api/1/privileges/{privilege_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Delete
      operationId: deletePrivilege
      summary: Delete a Privilege
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Get a Privilige
      operationId: getPrivilege
      summary: Get a Privilege
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Update privilege
      operationId: updatePrivilege
      summary: Update a Privilege
  '/api/1/privileges/{privilege_id}/roles':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: List roles for privilege
      operationId: listPrivelegeRoles
      summary: Get Roles assigned to Privilege
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: 'Add roles to privilege '
      operationId: addPrivilegeToRole
      summary: Assign a Privilege to Roles
  '/api/1/privileges/{privilege_id}/roles/{role_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Add roles to privilege
      operationId: deleteRoleFromPrivilege
      summary: Remove a Privilege from a Role
  '/api/1/privileges/{privilege_id}/users':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
        - Users
      description: Get Assigned Users
      operationId: getAssignedUser
      summary: Get Users assigned to a Privilege
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
        - Users
      description: Assign Users to Privilege
      operationId: assignUsersToPrivilege
      summary: Assign Users to a Privilege
  '/api/1/privileges/{privilege_id}/users/{user_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Privileges
      description: Remove a Privilege from Users
      operationId: removeUserFromPrivilege
      summary: Remove a Privilege from Users
  /api/1/roles:
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Roles
      description: Get Role by Name
      operationId: getRoleByName
      summary: Get Role by Name
  '/api/1/roles/{role_id}':
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Roles
      description: Get Role By ID
      operationId: getRoleById
      summary: Get Role by ID
  /api/1/saml_assertion:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Manage users
            - Manage All
      tags:
        - SAML Assertions
      description: Generate SAML Assertion
      operationId: generateSamlAssert
      summary: Generate SAML Assertion
  /api/1/saml_assertion/verify_factor:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Manage users
            - Manage All
      tags:
        - SAML Assertions
      description: 'Verify Factor: SAML'
      operationId: verFactorSaml
      summary: Verify Factor SAML
  /api/1/users:
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Users
      description: List Users
      operationId: listUsers
      summary: List Users by Account Name
    post:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Users
      description: Create a User
      operationId: createUser
      summary: Create a User
  /api/1/users/custom_attributes:
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Users
      description: Get Custom Attributes
      operationId: getCustomAttributes
      summary: Get Custom Attributes
  '/api/1/users/set_password_clear_text/{user_id}':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Users
      description: >-
        Update User password using their ID. This is done in cleartext and is
        insecure.
      operationId: updatePasswordInsecure
      summary: Set Password Using ID in Cleartext
  '/api/1/users/set_password_using_salt/{user_id}':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Users
      description: Update User Password Using ID and SHA-256 with salt.
      operationId: updatePasswordSecure
      summary: Set Password Using ID and SHA-256 and Salt
  '/api/1/users/{user_id}':
    delete:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Users
      description: Delete A User
      operationId: deleteUser
      summary: Delete a User
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Users
      description: Get User By ID
      operationId: getUserById
      summary: Get User by ID
    put:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Users
      description: Update a User
      operationId: updateUser
      summary: Update a User
  '/api/1/users/{user_id}/add_roles':
    put:
      security:
        - OAuth2:
            - Manage users
      tags:
        - Users
      description: Add Roles for a User
      operationId: addRolesToUser
      summary: Add Roles for a User
  '/api/1/users/{user_id}/apps':
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Users
      description: Get Apps for User
      operationId: getUserApps
      summary: Get Apps for a User
  '/api/1/users/{user_id}/auth_factor':
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Multi Factor Authentication V1
      description: Get MFA Factors
      operationId: getMFAFactors
      summary: Get Available Factors
  '/api/1/users/{user_id}/lock_user':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Users
      description: Lock User Account
      operationId: lockAccountUser
      summary: Lock User Account
  '/api/1/users/{user_id}/logout':
    put:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Authentication Only
      tags:
        - Users
      description: Log Out User
      operationId: logOutUser
      summary: Log User Out
  '/api/1/users/{user_id}/mfa_token':
    post:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Multi Factor Authentication V1
      description: Generate MFA Token
      operationId: generateMFAtoken
      summary: Generate Temp MFA Token
  '/api/1/users/{user_id}/otp_devices':
    get:
      security:
        - OAuth2:
            - Manage users
            - Manage All
            - Read All
            - Read Users
      tags:
        - Multi Factor Authentication V1
      description: Get Enrolled Factors
      operationId: getEnrolledFactors
      summary: Get Enrolled Factors
    post:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Multi Factor Authentication V1
      description: ' Enroll an Authentication Factor'
      operationId: enrollMfaFactor
      summary: Enroll a Factor
  '/api/1/users/{user_id}/otp_devices/{device_id}':
    delete:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Multi Factor Authentication V1
      description: Remove an enrolled MFA device for a user
      operationId: removeMfaFactors
      summary: Remove an Enrolled Factor
  '/api/1/users/{user_id}/otp_devices/{device_id}/trigger':
    post:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Multi Factor Authentication V1
      description: Activate a Factor
      operationId: activateMfaFactors
      summary: Activate a Factor
  '/api/1/users/{user_id}/otp_devices/{device_id}/verify':
    post:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Multi Factor Authentication V1
      description: Verify a Factor
      operationId: verifyMfaFactor
      summary: Verify a Factor
  '/api/1/users/{user_id}/remove_roles':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Users
      description: Remove Roles for a User
      operationId: removeUserRole
      summary: Remove Roles for a User
  '/api/1/users/{user_id}/roles':
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Users
      description: Get User Roles
      operationId: getUserRoles
      summary: Get Roles for a User
  '/api/1/users/{user_id}/set_custom_attributes':
    put:
      security:
        - OAuth2:
            - Manage users
            - Manage All
      tags:
        - Users
      description: Set Custom User Attributes
      operationId: setCustomAttributes
      summary: Set Custom Attributes for User
  '/api/1/users/{user_id}/set_state':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Users
      description: Set User State
      operationId: setUserState
      summary: Set User State
  /api/2/api_authorizations:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - API Authorization Server
      description: List Authorization Servers
      operationId: listAuthServers
      summary: List Api Auth Servers
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - API Authorization Server
      description: Create Auth Server
      operationId: createAuthServer
      summary: Create Api Auth Server
  '/api/2/api_authorizations/{api_auth_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - API Authorization Server
      description: Delete Authentication Server
      operationId: deleteAuthServer
      summary: Delete Api Auth Server
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - API Authorization Server
      description: Get Authorization Server
      operationId: getAuthServer
      summary: Get Api Auth Server
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - API Authorization Server
      description: Update Authorization Server
      operationId: updateAuthServer
      summary: Update Api Auth Server
  '/api/2/api_authorizations/{api_auth_id}/claims':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Claims'
      description: Get Authorization claims
      operationId: getAuthclaims
      summary: Get Api Auth Server claims
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Claims'
      description: Create Authorization Claim
      operationId: createAuthClaim
      summary: Create Api Auth Server Claim
  '/api/2/api_authorizations/{api_auth_id}/claims/{claim_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Claims'
      description: Delete Authorization Claim
      operationId: deleteAuthClaim
      summary: Delete Api Auth Server Claim
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Claims'
      description: Update Authorization Server Claim
      operationId: updateClaim
      summary: Update Api Auth Server Claim
  '/api/2/api_authorizations/{api_auth_id}/clients':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Client Apps'
      description: List Client Apps
      operationId: listClientApps
      summary: List Clients Apps
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Client Apps'
      description: Add Client App
      operationId: addClientApp
      summary: Add Client App
  '/api/2/api_authorizations/{api_auth_id}/clients/{client_app_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Client Apps'
      description: Delete Client App
      operationId: deleteClientApp
      summary: Remove Client App
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Client Apps'
      description: Update Client App
      operationId: updateClientApp
      summary: Update Client App
  '/api/2/api_authorizations/{api_auth_id}/scopes':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Scopes'
      description: List Authorization Scopes
      operationId: getScopes
      summary: Get Api Auth Server Scopes
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Scopes'
      description: Create API Auth Server Scope
      operationId: createScope
      summary: Create Api Auth Server Scope
  '/api/2/api_authorizations/{api_auth_id}/scopes/{scope_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Scopes'
      description: Delete Scope
      operationId: deleteScope
      summary: Delete Api Auth Server Scope
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - 'API Auth: Scopes'
      description: Update Scope
      operationId: updateScope
      summary: Update Api Auth Server Scope
  /api/2/apps:
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Apps
      description: List Apps
      operationId: listApps
      summary: List Apps
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Apps
      description: Create App
      operationId: createApp
      summary: Create App
  '/api/2/apps/{app_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Apps
      description: Delete App
      operationId: deleteApp
      summary: Delete App
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Apps
      description: Get App
      operationId: getApp
      summary: Get App
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Apps
      description: Update App
      operationId: updateApp
      summary: Update App
  '/api/2/apps/{app_id}/parameters/{parameter_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Apps
      description: Delete Parameter from App
      operationId: deleteAppParameter
      summary: Delete Parameter from App
  '/api/2/apps/{app_id}/rules':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: List App Rules
      operationId: listAppRules
      summary: List Rules
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Create App Rule
      operationId: createAppRule
  '/api/2/apps/{app_id}/rules/actions':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: List Actions
      operationId: listActions
      summary: List Actions
  '/api/2/apps/{app_id}/rules/actions/{rule_action_value}/values':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Sort App rules
      operationId: listActionValies
      summary: List Actions Values
  '/api/2/apps/{app_id}/rules/conditions':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: List App Conditions
      operationId: listConditions
      summary: List Conditions
  '/api/2/apps/{app_id}/rules/conditions/{rule_condition_value}/operators':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: List Condition Operators
      operationId: listConditionOperators
      summary: List Conditions Operators
  '/api/2/apps/{app_id}/rules/conditions/{rule_condition_value}/values':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: List Condition Values
      operationId: listConditionValues
      summary: List Conditions Values
  '/api/2/apps/{app_id}/rules/sort':
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Sort App rules
      operationId: sortAppRules
      summary: Bulk Sort
  '/api/2/apps/{app_id}/rules/{rule_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Delete App Rule
      operationId: deleteRule
      summary: Delete Rule
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Get App Rule
      operationId: getAppRule
      summary: Get Rule
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - App Rules
      description: Update App Rule.
      operationId: updateAppRule
      summary: Update Rule
  '/api/2/apps/{app_id}/users':
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Apps
      description: Get App Users
      operationId: getAppUsers
      summary: Get App Users
  /api/2/connectors:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Apps
      description: List Connectors
      operationId: listConnectors
      summary: List Connectors
  /api/2/mappings:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List Mappings
      operationId: listMappings
      summary: List Mappings
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: Create User Mapping
      operationId: createMapping
      summary: Create Mapping
  /api/2/mappings/actions:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List User Mappings' Actions
      operationId: listMappingsActions
      summary: List Actions
  '/api/2/mappings/actions/{mapping_action_value}/values':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List User Mappings' Actions' Values
      operationId: listMappingActionValues
      summary: List Actions Values
  /api/2/mappings/conditions:
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List User Mappings' Conditions
      operationId: listMappingConditions
      summary: List Conditions
  '/api/2/mappings/conditions/{mapping_condition_value}/operators':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List User Mappings' Conditions' Operators
      operationId: listMappingConditionsOperators
      summary: List Conditions Operators
  '/api/2/mappings/conditions/{mapping_condition_value}/values':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: List User Mappings'  Conditions' Values
      operationId: listMappingContionValues
      summary: List Conditions Values
  /api/2/mappings/sort:
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: Bulk Sort User Mappings
      operationId: sortMappings
      summary: Bulk Sort
  '/api/2/mappings/{mapping_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: Delete User Mapping
      operationId: deleteMapping
      summary: Delete Mapping
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: Get User Mapping
      operationId: getMapping
      summary: Get Mapping
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - User Mappings
      description: Update User Mapping
      operationId: updateMapping
      summary: Update Mapping
  '/api/2/mfa/users/{user_id}/devices':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Get a user authentication devices
      operationId: getAuthenticationDevices
      summary: Get User Devices
  '/api/2/mfa/users/{user_id}/devices/{device_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Delete a user\'s authentication device
      operationId: deleteEnrolledFactor
      summary: Delete Enrolled Factor
  '/api/2/mfa/users/{user_id}/factors':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Get a user\'s available authentication factors
      operationId: getAuthFactors
      summary: Get User Factors
  '/api/2/mfa/users/{user_id}/mfa_token':
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Create new MFA token on the user's account
      operationId: generateOTP
      summary: Generate MFA token
  '/api/2/mfa/users/{user_id}/registrations':
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Create a new registration process
      operationId: createFactorRegistration
      summary: Create Factor Registration
  '/api/2/mfa/users/{user_id}/registrations/{registration_id}':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Get registration state by id
      operationId: getUserRegistration
      summary: Get User Registration
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Submit an otp for verification.
      operationId: verifyUserRegistration
      summary: Verify User Registration
  '/api/2/mfa/users/{user_id}/verifications':
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Create a new verification process
      operationId: createDeviceVerification
      summary: Create Device Verification
  '/api/2/mfa/users/{user_id}/verifications/{verification_id}':
    get:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Get verification state by id
      operationId: getUserVerification
      summary: Get User Verification
    put:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Multi Factor Authentication
      description: Submit an otp for verification.
      operationId: verifyUserVerification
      summary: Verify User Verification
  /api/2/risk/events:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: Track Vigilance AI (Risk Service) Event
      operationId: trackRiskEvent
      summary: Track an Event
  /api/2/risk/rules:
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: List Vigilance AI (Risk Service) Rules
      operationId: listRiskRules
      summary: List Rules
    post:
      security:
        - OAuth2:
            - Manage All
      tags:
        - Vigilance AI
      description: Create Vigilance AI (Risk Service) Rule
      operationId: createRiskRule
      summary: Create Rule
  '/api/2/risk/rules/{rule_id}':
    delete:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: Delete Vigilance AI (Risk Service)
      operationId: deleteRiskRule
      summary: Delete Rule
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: >-
        Use this API to return a single rule that has been created in the Risk
        Sevice.
      operationId: getRiskRule
      summary: get Risk Rule
    put:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: Update Vigilance AI (Risk Service) Rule
      operationId: updateRiskRule
      summary: Update Rule
  /api/2/risk/scores:
    get:
      security:
        - OAuth2:
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: Get Vigilance AI (Risk Service) Score Summary
      operationId: getRiskScores
      summary: Get Score Summary
  /api/2/risk/verify:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - Vigilance AI
      description: Get Vigilance AI (Risk Service) Score
      operationId: getRiskScore
      summary: Get a Risk Score
  /api/2/saml_assertion:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Manage users
            - Manage All
      tags:
        - SAML Assertions
      description: Generate SAML Assertion
      operationId: generateSamlAssert2
      summary: Generate SAML Assertion
  /api/2/saml_assertion/verify_factor:
    post:
      security:
        - OAuth2:
            - Authentication Only
            - Manage users
            - Manage All
      tags:
        - SAML Assertions
      description: 'Verify Factor: SAML'
      operationId: verFactorSaml2
      summary: Verify Factor SAML
  /auth/oauth2/revoke:
    post:
      security:
        - basicAuth: []
      tags:
        - OAuth2
      description: Revoke Tokens
      operationId: revokeTokens
      summary: Revoke Tokens
  /auth/oauth2/v2/token:
    post:
      security:
        - basicAuth: []
      tags:
        - OAuth2
      description: Generate Tokens
      operationId: generateToken
      summary: Generate Tokens
  /auth/rate_limit:
    get:
      security:
        - OAuth2:
            - Read Users
            - Manage users
            - Manage All
            - Read All
      tags:
        - OAuth2
      description: Get Rate Limit
      operationId: getRateLimit
      summary: Get Rate Limit
securityDefinitions:
  OAuth2:
    description: >-
      This API uses OAuth2 with the Client Credential grant flow. [More
      info](https://api.example.com/docs/auth)
    flow: application
    scopes:
      Authentication Only: perform POST calls only to authentication endpoints
      Manage All: >-
        Gives the credential pair the ability to generate an access token that
        can perform GET, POST, PUT, and DELETE calls for all available API
        resources, including the ability to set passwords and assign and remove
        roles.
      Manage users: >-
        can perform GET, POST, PUT, and DELETE calls available for the User,
        Role, and Group API resources, with the exception of setting passwords
        and assigning and removing roles
      Read All: >-
        Gives the credential pair the ability to generate an access token that
        can perform GET calls available for all API resources.
      Read Users: >-
        can perform GET calls available for the User, Role, and Group API
        resources.
    tokenUrl: https://api.us.onelogin.com/auth/oauth2/v2/token
    type: oauth2
  basicAuth:
    type: basic
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
tags:
  - description: OAuth2
    name: OAuth2
  - description: >-
      Collection of APIs that allow you to configure OneLogin as an
      Authorization server
    name: API Authorization Server
  - description: Access and Authorization Scopes
    name: 'API Auth: Scopes'
  - description: Regarding Token Claims
    name: 'API Auth: Claims'
  - name: 'API Auth: Client Apps'
  - description: App Management Endpoint
    name: Apps
  - description: Dealing with SAML Authentication protocol
    name: SAML Assertions
  - description: User Mappings Management Endpoint
    name: User Mappings
  - description: Risk service Endpoint
    name: Vigilance AI
  - description: Application Rule policy creation and enforcement
    name: App Rules
  - description: 'Event Types, IDs, tracking, tracing, and more'
    name: Events
  - description: Group Management Endpoint
    name: Groups
  - description: Invite Via Email Link
    name: Invite Links
  - description: 'Multi Factor Authentication (MFA), One Time Passcodes (OTP)'
    name: Multi Factor Authentication
  - description: 'Deprecated Multi Factor Authentication (MFA), One Time Passcodes (OTP)'
    name: Multi Factor Authentication V1
  - description: Privilege Management Endpoint
    name: Privileges
  - description: Role Management Endpoint
    name: Roles
  - description: User Management Endpoint
    name: Users
x-components: {}

